# Generated by Django 4.2 on 2023-04-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collections1')
        """, """
            DELETE FROM store_collection
            WHERE title = 'collections1'
        """)
    ]
